import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Header from './components/Header'
import Main from './components/Main'
import Footer from './components/Footer'
import 'animate.css';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </Head>
      <Header />
      <Main />
      <Footer />
    </>
  )
}
