import Head from 'next/head'
import styles from '@/styles/Home.module.css'

export default function Footer() {
  return (
    <>
      <Head>
        <title>footer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <footer className={styles.footer_container}>

      <h2 className={styles.footer_h2}>COPYRIGHT © 環境開発株式会社 ALL RIGHTS RESERVED.</h2>
      </footer>
    </>
  )
}
