import Head from 'next/head'
import styles from '@/styles/Home.module.css'

export default function Header() {
  return (
    <>
      <Head>
        <title>header</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
      </Head>
      <div className={styles.header_container}>
        <h1 className={styles.company_name}>
          <a href="/">
            <span class="material-symbols-outlined">
              public
            </span>
            環境開発株式会社
          </a>
        </h1>
        <div className={styles.menu_wrapper}>

          <ul className={styles.header_menu_ul}>
            <li>
              <a className={styles.header_a} href="/">
                Top
              </a>
            </li>
            <li>
              <a className={styles.header_a} href="/components/about">
                About
              </a>
            </li>
            <li>
              <a className={styles.header_a} href="/components/product">
                Products
              </a>
            </li>
            <li>
              <a className={styles.header_a} href="/components/information">
                Information
              </a>
            </li>
            <li>
              <a className={styles.header_a} href="/components/contact">
                Contact
              </a>
            </li>
          </ul>
        </div>
      </div>
    </>
  )
}
