import Head from 'next/head'
import styles from '@/styles/Home.module.css'

export default function Header() {
  return (
    <>
      <Head>
        <title>header</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <a href="/">
          <h1 className='company_name'>環境開発株式会社</h1>
        </a>
      <div className={styles.header_wrapper}>
        <ul className={styles.header_menu_ul}>
          <a className={styles.header_a} href="/">
            <li>Top</li>
          </a>
          <a className={styles.header_a} href="/components/about">
            <li>About</li>
          </a>
          <a className={styles.header_a} href="/components/product">
            <li>Products</li>
          </a>
          <a className={styles.header_a} href="/components/information">
            <li>Information</li>
          </a>
          <a className={styles.header_a} href="/components/contact">
            <li>Contact</li>
          </a>
        </ul>
      </div>
    </>
  )
}
