import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Header from './Header'
import Footer from './Footer'

export default function information() {
    return (
        <>
            <Head>
                <title>information</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <div className={`contentsMain ${styles.information_container}`}>
                <main>
                    <h3>information</h3>
                </main>
                <Footer />
            </div>
        </>
    )
}
