import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import main_pic from '../../public/img/main_pic.jpeg'
import Image from 'next/image'

export default function Main() {
    return (
        <>
            <Head>
                <title>Main</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={`contentsMain ${styles.main_container}`}>
                <Image className={styles.main_image_pic} src={main_pic} alt='top-pic' />
                <h2 className={styles.main_h2}>明るい未来へあなたと共に</h2>
            </div>
        </>
    )
}
