import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import main_pic from '../../public/img/main_pic.jpeg'
import Image from 'next/image'

export default function Main() {
    return (
        <>
            <Head>
                <title>Main</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.main_container}>
                <div className={styles.dummy_div}>dummy as a picture</div>
                {/* <Image src={main_pic} /> */}
                <div className={styles.main_wrapper}>
                    <h2 className={styles.main_h2}>Main</h2>
                </div>
            </div>
        </>
    )
}
