import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Header from './Header'
import Footer from './Footer'

export default function product() {
    return (
        <>
            <Head>
                <title>product</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.product_container}>
                <Header />
                <main>
                    <h3>product</h3>
                </main>
                <Footer />
            </div>
        </>
    )
}
